import { WTCScene } from './scene.js';
import { collapseSeconds } from './dynamics.js';
import {towers,clamp,steelAt,steelTable,stateAt,heatingCurve} from './model.js';
const $=id=>document.getElementById(id);
let towerIndex=0,t=0,playing=false,view='exterior',dirty=true;
const descriptions=[['Built to distribute loads','Closely spaced perimeter columns form a stiff exterior tube. Interior core columns carry gravity loads; floor systems connect the two and provide lateral support.','Before impact','A perimeter tube, an interior core, and connecting floors.'],['Impact and load redistribution','The aircraft severed and damaged columns and floors. Surviving members took redistributed loads. Debris also stripped insulation from some steel; the tower remained standing after impact.','Aircraft impact','Damage to columns, floors, and fireproofing.'],['Fires heat exposed members','Jet fuel ignited fires across several floors. Office contents sustained the burning. Heating varied by location, ventilation, insulation, and member size. Visible flames and smoke are illustrative; they are not temperature measurements.','Fire after impact','Office fires persist after the initial fuel fireball.'],['Deformation changes the load path','Heated floor systems sagged while many connections remained attached. This could pull perimeter columns inward; the damaged, heated core also weakened. Visible bowing and computed structural response informed NIST’s sequence.','Sagging and inward bowing','Switch to the floor mechanism to see the connection.'],['Instability at the damaged zone','NIST’s proposed sequence culminates in instability of the affected perimeter wall and downward motion of the upper section. This model uses the historical timing; it does not calculate a failure time.','Collapse initiation','Loss of stability at the fire- and impact-affected floors.'],['Gravity drives the progression','Once downward motion began, dynamic loads overwhelmed the structure below. The main descent uses a reduced gravity-and-mass-capture model with assumed resistance. Fragment release, tilt, and surviving core sections remain illustrative; the model is not fitted to the historical collapse duration.','Collapse progression','Illustrative animation beyond collapse initiation.']];
function updateUI(){const s=stateAt(t,towerIndex),d=s.d,desc=descriptions[s.phase];$('sceneEyebrow').textContent=d.short+' · '+d.name.toUpperCase();$('sceneTitle').textContent=view==='detail'?'How a floor pulls inward':desc[2];$('sceneCaption').textContent=view==='detail'?'Core → floor truss → perimeter column. Deformation exaggerated.':desc[3];$('phaseTitle').textContent=desc[0];$('phaseBody').textContent=desc[1]+(s.phase===3||s.phase===4?' The principal inward-bowing face was the '+d.face+' face of '+d.short+'.':'');$('flight').textContent=d.flight;$('impactFloors').textContent=d.low+'–'+d.high;$('impactSpeed').textContent=d.speed;$('duration').textContent='≈ '+d.minutes+' minutes';$('scaleLabel').textContent=view==='detail'?'60 ft span · schematic section':d.height+' m · 110 floors';$('modelBadge').textContent=view==='detail'?'Deformation exaggerated · no structural solver':s.phase===5?'REDUCED DESCENT MODEL · assumed resistance':'Source-informed reconstruction · approximate geometry';const mins=d.hour*60+d.minute+Math.round(s.minutes);$('clock').textContent=s.phase===5?'Model +'+collapseSeconds(t).toFixed(1)+' s':Math.floor(mins/60)+':'+String(mins%60).padStart(2,'0')+' a.m.';$('elapsed').textContent=t<8?'Before impact':s.phase===5?'Not a historical collapse clock':'≈ '+Math.round(s.minutes)+' min after impact';$('timeline').value=t;$('viewTimeline').value=t;$('viewPlay').textContent=playing?'Ⅱ':'▶';for(let i=0;i<5;i++)$('step'+i).classList.toggle('lit',s.phase>=i+1);document.querySelectorAll('[data-stage]').forEach((b,i)=>b.classList.toggle('current',i===s.phase));$('play').innerHTML=playing?'Ⅱ <span>Pause sequence</span>':'▶ <span>Play sequence</span>';$('play').setAttribute('aria-label',playing?'Pause sequence':'Play sequence');}
function setTime(value){t=clamp(value,0,120);dirty=true;updateUI();}
$('play').onclick=()=>{if(t>=120)t=0;playing=!playing;updateUI();};$('restart').onclick=()=>{playing=false;setTime(0);};$('viewPlay').onclick=()=>$('play').click();$('viewTimeline').oninput=e=>{playing=false;setTime(+e.target.value);};$('timeline').oninput=e=>{playing=false;setTime(+e.target.value);};document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>{playing=false;setTime(+b.dataset.stage);});document.querySelectorAll('[data-tower]').forEach(b=>b.onclick=()=>{towerIndex=+b.dataset.tower;document.querySelectorAll('[data-tower]').forEach(c=>{c.classList.toggle('active',b===c);c.setAttribute('aria-pressed',b===c?'true':'false');});if(visual)visual.select(towerIndex);playing=false;setTime(0);});
function panel(steel){$('sequencePanel').hidden=steel;$('steelPanel').hidden=!steel;$('sequenceTab').setAttribute('aria-selected',String(!steel));$('steelTab').setAttribute('aria-selected',String(steel));}
$('sequenceTab').onclick=()=>panel(false);$('steelTab').onclick=()=>panel(true);[$('sequenceTab'),$('steelTab')].forEach(b=>b.onkeydown=e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const steel=b===$('sequenceTab');panel(steel);(steel?$('steelTab'):$('sequenceTab')).focus();}});
$('sourcesOpen').onclick=()=>$('sources').showModal();$('sourcesClose').onclick=()=>$('sources').close();$('sources').onclick=e=>{if(e.target===$('sources')){const r=$('sources').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('sources').close();}};
function updateSteel(){const temp=+$('temperature').value,m=steelAt(temp,+$('grade').value);$('tempOutput').textContent=temp.toLocaleString()+'°C';$('yieldValue').textContent=Math.round(m.yieldMPa)+' MPa';$('yieldPct').textContent=Math.round(m.ky*100)+'% of ambient value';$('stiffValue').textContent=m.modulusGPa.toFixed(1)+' GPa';$('stiffPct').textContent=(m.ke*100).toFixed(1)+'% of ambient value';$('expansionValue').textContent=Math.round(m.expansionMM)+' mm';$('expansionBar').style.width=(m.expansionMM/215.1*100)+'%';const x=T=>30+(T-20)/980*278,y=k=>120-k*100;const path=col=>steelTable.map((r,i)=>(i?'L':'M')+x(r[0]).toFixed(1)+','+y(r[col]).toFixed(1)).join(' ');$('strengthChart').innerHTML=`<g font-family="sans-serif" font-size="10" fill="#8fa6b5"><text x="1" y="23">100%</text><text x="5" y="74">50%</text><text x="15" y="123">0</text><text x="30" y="143">20°C</text><text x="265" y="143">1,000°C</text></g><path d="M30,20H310M30,70H310M30,120H310" stroke="#34444f" fill="none"/><path d="${path(1)}" stroke="#f2a768" stroke-width="2.5" fill="none"/><path d="${path(2)}" stroke="#7fbdde" stroke-width="2.5" fill="none"/><path d="M${x(temp)},15V125" stroke="#d9e3e8" stroke-dasharray="3,4"/><circle cx="${x(temp)}" cy="${y(m.ky)}" r="4" fill="#f2a768"/><circle cx="${x(temp)}" cy="${y(m.ke)}" r="4" fill="#7fbdde"/>`;}
$('temperature').oninput=updateSteel;$('grade').onchange=updateSteel;
function updateHeating(){const gas=+$('gasTemp').value,minute=+$('heatTime').value,bare=heatingCurve(gas,0),protectedSteel=heatingCurve(gas,20);$('gasOutput').textContent=gas+'°C';$('heatTimeOutput').textContent=minute+' min';$('bareTemp').textContent=Math.round(bare[minute])+'°C';$('protectedTemp').textContent=Math.round(protectedSteel[minute])+'°C';const x=m=>32+m/60*273,y=T=>122-T/1000*102,path=values=>values.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+','+y(v).toFixed(1)).join(' ');$('heatChart').innerHTML=`<g font-family="sans-serif" font-size="10" fill="#8fa6b5"><text x="0" y="23">1000</text><text x="10" y="74">500</text><text x="20" y="125">0</text><text x="32" y="144">0 min</text><text x="272" y="144">60 min</text></g><path d="M32,20H308M32,71H308M32,122H308" stroke="#34444f"/><path d="M32,${y(gas)}H308" stroke="#788b97" stroke-dasharray="2 4"/><path d="${path(bare)}" stroke="#f2a768" stroke-width="2.5" fill="none"/><path d="${path(protectedSteel)}" stroke="#7fbdde" stroke-width="2.5" fill="none"/><path d="M${x(minute)},15V125" stroke="#d9e3e8" stroke-dasharray="3 4"/><circle cx="${x(minute)}" cy="${y(bare[minute])}" r="4" fill="#f2a768"/><circle cx="${x(minute)}" cy="${y(protectedSteel[minute])}" r="4" fill="#7fbdde"/>`;}
$('gasTemp').oninput=updateHeating;$('heatTime').oninput=updateHeating;updateHeating();


let visual=null, last=0, uiAccumulator=0;
const viewport=$('viewport');
function resetCamera(){visual?.resetCamera();}
function changeView(value){view=value;$('view').value=value;visual?.setView(value);updateUI();}
$('view').onchange=e=>changeView(e.target.value);
$('showMechanism').onclick=()=>{changeView('detail');playing=false;setTime(90);viewport.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});};
$('resetCamera').onclick=resetCamera;
$('focusDamage').onclick=()=>{if(view==='detail')changeView('cutaway');visual?.focusDamage();};
$('zoomIn').onclick=()=>visual?.zoom(.8);$('zoomOut').onclick=()=>visual?.zoom(1.25);
$('quality').onchange=e=>{if(!visual)return;visual.renderer.setPixelRatio(e.target.value==='high'?Math.min(devicePixelRatio,2):Math.min(devicePixelRatio,1.25));visual.renderer.shadowMap.enabled=e.target.value==='high';visual.renderer.setSize(viewport.clientWidth,viewport.clientHeight);};
$('fullscreen').onclick=async()=>{if(!document.fullscreenElement){if(viewport.requestFullscreen){try{await viewport.requestFullscreen();}catch{viewport.classList.toggle('expanded');}}else viewport.classList.toggle('expanded');}else await document.exitFullscreen();};
$('closeExpanded').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();viewport.classList.remove('expanded');};
try{visual=new WTCScene(viewport);visual.update(0);$('sceneLoading').hidden=true;}catch(error){$('sceneLoading').hidden=true;$('webglError').hidden=false;console.error(error);}
function animate(now){requestAnimationFrame(animate);if(document.hidden){last=now;return;}const dt=last?Math.min((now-last)/1000,.05):0;last=now;
 if(playing){const rate=t<8?1.7:t<10?.55:t<98?2.5:t<100?.7:.75;t=Math.min(120,t+dt*rate*+$('speed').value);if(t===120)playing=false;uiAccumulator+=dt;if(uiAccumulator>.09||t===120){updateUI();uiAccumulator=0;}}
 if(visual)visual.update(t);
}
document.addEventListener('visibilitychange',()=>{last=0;});updateSteel();updateUI();requestAnimationFrame(animate);
